name: Probando XML
run-name: ${{ github.workflow }} by @${{ github.actor }} y entornos ninguno

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  PrepareAPKandTest:
    name: Prepare APK and test QA results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Prepare APK
        run: echo 'run ./gradle with parameter'

      - name: Run QA tests
        run: echo 'Run QA tests'

      - name: Check xml results
        uses: mavrosxristoforos/get-xml-info@1.1.1
        id: totalvalue
        with:
          xml-file: 'resources/testng-results.xml'
          xpath: '//testng-results/@total'
      - name: Check xml results
        uses: mavrosxristoforos/get-xml-info@1.1.1
        id: passedvalue
        with:
          xml-file: 'resources/testng-results.xml'
          xpath: '//testng-results/@passed'

      - name: Show Data totalvalue
        run: echo 'totalvalue:${{ steps.totalvalue.outputs.info }}'
      - name: Show Data passedvalue
        run: echo 'passedvalue:${{ steps.passedvalue.outputs.info }}'

      - name: Comparar valores
        run: |
          total=${{ steps.totalvalue.outputs.info }}
          passed=${{ steps.passedvalue.outputs.info }}
          if [ "$total" -gt "$passed" ]; then
            echo "El valor de Total es mayor que Passed."
            exit 1
          fi
      - name: Publish Test Report
        uses: starburstdata/action-testng-report@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
