name: Team-DevOps
run-name: ${{ github.workflow }} by @${{ github.actor }}

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  PrepareAPKandTest:
    name: Prepare APK and test QA results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Prepare APK
        run: echo 'run ./gradle with parameter'

      - name: Run QA tests
        run: echo 'Run QA tests'

      - name: Check xml results
        uses: mavrosxristoforos/get-xml-info@1.1.1
        id: totalvalue
        with:
          xml-file: 'resources/testng-results.xml'
          xpath: '//testng-results/@total'
      - name: Check xml results
        uses: mavrosxristoforos/get-xml-info@1.1.1
        id: passedvalue
        with:
          xml-file: 'resources/testng-results.xml'
          xpath: '//testng-results/@passed'

      - name: Show Data totalvalue
        run: echo 'totalvalue:${{ steps.totalvalue.outputs.info }}'
      - name: Show Data passedvalue
        run: echo 'passedvalue:${{ steps.passedvalue.outputs.info }}'

      - name: Compare results
        if: ${{ steps.totalvalue.outputs.info }} > ${{ steps.passedvalue.outputs.info }}
        run: exit 1
